/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Product;

import com.pharmacy.app.BUS.MedicalProductsBUS;
import com.pharmacy.app.BUS.ProductBatchBUS;
import com.pharmacy.app.DTO.MedicalProductsDTO;
import com.pharmacy.app.DTO.ProductBatchDTO;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author LENOVO
 */
public class MedicalProducts extends javax.swing.JPanel {
    MedicalProductsBUS medBUS = new MedicalProductsBUS();
    /**
     * Creates new form MedicinesBatch
     */
    public MedicalProducts() {
        initComponents();
        medListTbl.setDefaultEditor(Object.class, null);
        loadMedList();
        batchListTbl.setDefaultEditor(Object.class, null);
        loadBatchList();
        dateTbl.setDefaultEditor(Object.class, null);
        loadDateList();
        setupTableRenderer();
        centerTableContent(dateTbl);
        centerTableContent(batchListTbl);
        centerTableContent(medListTbl);
        
        searchPdtxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchProduct();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchProduct();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchProduct();

            }
        });
    }
    
    private void centerTableContent(JTable table) {
        // Căn giữa tiêu đề
        JTableHeader header = table.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Căn giữa nội dung
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    
    private void searchProduct() {
        String keyword = searchPdtxt.getText();
        ArrayList<MedicalProductsDTO> result = medBUS.searchAll(keyword);
        showDataToTable(result);
    }
    public void showDataToTable(ArrayList<MedicalProductsDTO> list) {
        DefaultTableModel model = (DefaultTableModel) medListTbl.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        int stt = 1;
        for (MedicalProductsDTO product : list) {
            model.addRow(new Object[]{
                stt++,
                product.getMedicineID(),
                product.getName(),
                product.getQuantity(),
                product.getCategory(),
                product.getStatus()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        medListPn = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        searchPdtxt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        medListTbl = new javax.swing.JTable();
        medBatPn = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        searchPBtxt = new javax.swing.JTextField();
        refreshBtn1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchListTbl = new javax.swing.JTable();
        medDatePn = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        refreshBtn2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dateTbl = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(231, 231, 231));

        medListPn.setBackground(new java.awt.Color(255, 255, 255));
        medListPn.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(608, 90));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("DANH SÁCH SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 264, 0, 0);
        jPanel8.add(jLabel5, gridBagConstraints);

        addBtn.setText("THÊM THUỐC MỚI");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 30, 0, 101);
        jPanel8.add(addBtn, gridBagConstraints);

        refreshBtn.setText("TẢI LẠI");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        jPanel8.add(refreshBtn, gridBagConstraints);

        searchPdtxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchPdtxt.setForeground(new java.awt.Color(204, 204, 204));
        searchPdtxt.setText("Nhập tên sản phẩm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 12, 0);
        jPanel8.add(searchPdtxt, gridBagConstraints);

        medListPn.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setEnabled(false);

        medListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "PHÂN LOẠI", "TRẠNG THÁI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        medListTbl.setRowHeight(30);
        medListTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medListTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(medListTbl);

        jPanel9.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        medListPn.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Danh sách sản phẩm", medListPn);

        medBatPn.setBackground(new java.awt.Color(255, 255, 255));
        medBatPn.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(562, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("DANH SÁCH LÔ SẢN PHẨM");

        searchPBtxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        searchPBtxt.setForeground(new java.awt.Color(204, 204, 204));
        searchPBtxt.setText("Nhập tên sản phẩm");

        refreshBtn1.setText("TẢI LẠI");
        refreshBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(searchPBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(refreshBtn1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refreshBtn1)
                    .addComponent(searchPBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        medBatPn.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setEnabled(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(352, 202));

        batchListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ LÔ", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "NHÀ CUNG CẤP", "NSX", "HSD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        batchListTbl.setRowHeight(30);
        jScrollPane2.setViewportView(batchListTbl);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        medBatPn.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Danh sách lô sản phẩm", medBatPn);

        medDatePn.setBackground(new java.awt.Color(255, 255, 255));
        medDatePn.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(562, 90));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("QUẢN LÝ HẠN SỬ DỤNG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 217, 0, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setText("HẠN SỬ DỤNG CÒN LẠI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 93, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 6 tháng", "Dưới 3 tháng", "Đã hết hạn" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 34, 18, 0);
        jPanel4.add(jComboBox2, gridBagConstraints);

        refreshBtn2.setText("TẢI LẠI");
        refreshBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 18, 148);
        jPanel4.add(refreshBtn2, gridBagConstraints);

        medDatePn.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setEnabled(false);

        dateTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ LÔ", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "NHÀ CUNG CẤP", "NSX", "HSD", "HSD CÒN LẠI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dateTbl.setRowHeight(30);
        jScrollPane1.setViewportView(dateTbl);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        medDatePn.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quản lý hạn sử dụng", medDatePn);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        AddProduct addDialog = new AddProduct((Frame)SwingUtilities.getWindowAncestor(addBtn), true);
        addDialog.setLocationRelativeTo(null);
        addDialog.setVisible(true);
    }//GEN-LAST:event_addBtnMouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    private void loadMedList(){
        ArrayList<MedicalProductsDTO> medList = medBUS.getAllProducts();
        DefaultTableModel model = (DefaultTableModel) medListTbl.getModel();
        model.setRowCount(0);
        int stt = 1;
        for(MedicalProductsDTO med : medList){
            model.addRow(new Object[]{
                stt++,
                med.getMedicineID(),
                med.getName(),
                med.getQuantity(),
                med.getCategory(),
                med.getStatus()
            });
        }
    }
    
    private void loadBatchList(){
        try {
            ProductBatchBUS medBUS = new ProductBatchBUS();
            ArrayList<ProductBatchDTO> batchList = medBUS.getAllBatches();
            DefaultTableModel model = (DefaultTableModel) batchListTbl.getModel();
            model.setRowCount(0);

            for(ProductBatchDTO batch : batchList){
                model.addRow(new Object[]{
                    batch.getBatchID(),
                    batch.getMedicineID(),
                    batch.getQuantityInStock(),
                    "supplier chưa xử lý",
                    batch.getManufacturingDate(),
                    batch.getExpirationDate()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            e.getMessage();
        }
            
}
    private void loadDateList(){
        try {
            ProductBatchBUS medBUS = new ProductBatchBUS();
            ArrayList<ProductBatchDTO> batchList = medBUS.getAllBatches();
            DefaultTableModel model = (DefaultTableModel) dateTbl.getModel();
            model.setRowCount(0);

            for(ProductBatchDTO batch : batchList){
                model.addRow(new Object[]{
                    batch.getBatchID(),
                    batch.getMedicineID(),
                    batch.getQuantityInStock(),
                    "supplier chưa xử lý",
                    batch.getManufacturingDate(),
                    batch.getExpirationDate(),
                    medBUS.getDateforBatch(batch.getExpirationDate())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            e.getMessage();
        }
    }
    
    private void setupTableRenderer() {
        dateTbl.getColumnModel().getColumn(6)
            .setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {

                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    c.setForeground(Color.BLACK);

                    try {
                        String text = value.toString(); // "1 năm 2 tháng"
                        int years = 0, months = 0;
                        if (text.contains("năm")) years = Integer.parseInt(text.split(" năm")[0].trim());
                        if (text.contains("tháng")) {
                            String afterYear = text.contains("năm") ? text.split("năm")[1] : text;
                            months = Integer.parseInt(afterYear.split("tháng")[0].trim());
                        }

                        int totalMonths = years * 12 + months;
                        if (totalMonths < 6) c.setForeground(Color.RED);

                    } catch (Exception e) {
                        c.setForeground(Color.BLACK);
                    }

                    return c;
                }
            });
    }   
    
    private void medListTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medListTblMouseClicked
         
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = medListTbl.getSelectedRow();
            if (row >= 0) {
                String ID = medListTbl.getValueAt(row, 0).toString();
                
                MedicalProductsDTO selectedProduct = medBUS.getProductByID(ID);
                // Mở dialog
                Frame frame = JOptionPane.getFrameForComponent(medListTbl);
                ProductDetails dialog = new ProductDetails(frame, true, selectedProduct);
                dialog.setLocationRelativeTo(frame);
                dialog.setVisible(true);
            }
        }



    }//GEN-LAST:event_medListTblMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadMedList();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void refreshBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtn1ActionPerformed
        loadBatchList();
    }//GEN-LAST:event_refreshBtn1ActionPerformed

    private void refreshBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtn2ActionPerformed
        loadDateList();
    }//GEN-LAST:event_refreshBtn2ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable batchListTbl;
    private javax.swing.JTable dateTbl;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel medBatPn;
    private javax.swing.JPanel medDatePn;
    private javax.swing.JPanel medListPn;
    private javax.swing.JTable medListTbl;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton refreshBtn1;
    private javax.swing.JButton refreshBtn2;
    private javax.swing.JTextField searchPBtxt;
    private javax.swing.JTextField searchPdtxt;
    // End of variables declaration//GEN-END:variables
}

