/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Requests;

import com.pharmacy.app.BUS.RequestBUS;
import com.pharmacy.app.DTO.RequestDTO;
import com.pharmacy.app.DTO.SessionDTO;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author phong
 */
public class AddRequest extends javax.swing.JDialog {
    RequestBUS reqBUS = new RequestBUS();
    /**
     * Creates new form AddRequest
     */
    public AddRequest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtRequestID.setText(reqBUS.generateNextProductID());
        txtRequestDate.setText(LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRequest = new javax.swing.JPanel();
        lblRequest = new javax.swing.JLabel();
        pnlRequestFields = new javax.swing.JPanel();
        lblRequestType = new javax.swing.JLabel();
        txtRequestDate = new javax.swing.JTextField();
        cbRequestType = new javax.swing.JComboBox<>();
        lblRequestDate = new javax.swing.JLabel();
        lblLeaveStartDate = new javax.swing.JLabel();
        lblLeaveEndDate = new javax.swing.JLabel();
        lblReason = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        lblRequestID = new javax.swing.JLabel();
        txtRequestID = new javax.swing.JTextField();
        startDatePicker = new com.toedter.calendar.JDateChooser();
        endDatePicker = new com.toedter.calendar.JDateChooser();
        pnlButton = new javax.swing.JPanel();
        btnSendRequest = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequest.setText("THÔNG TIN ĐƠN");
        pnlRequest.add(lblRequest);

        pnlRequestFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRequestType.setText("Loại đơn:");
        pnlRequestFields.add(lblRequestType, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 75, -1));

        txtRequestDate.setEditable(false);
        pnlRequestFields.add(txtRequestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 98, 200, -1));

        cbRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn xin nghỉ phép", "Đơn xin nghỉ phép không lương", "Đơn xin thôi việc", "Đơn xin nghỉ ốm", "Đơn xin nghỉ thai sản", "Đơn xin nghỉ lý do khác" }));
        pnlRequestFields.add(cbRequestType, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 46, -1, -1));

        lblRequestDate.setText("Ngày gửi đơn:");
        pnlRequestFields.add(lblRequestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, -1, -1));

        lblLeaveStartDate.setText("Ngày nghỉ:");
        pnlRequestFields.add(lblLeaveStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 75, -1));

        lblLeaveEndDate.setText("Ngày quay lại:");
        pnlRequestFields.add(lblLeaveEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        lblReason.setText("Lí do:");
        pnlRequestFields.add(lblReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 257, 75, -1));
        pnlRequestFields.add(txtReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 190, -1));

        lblRequestID.setText("Mã đơn:");
        pnlRequestFields.add(lblRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 75, -1));

        txtRequestID.setEditable(false);
        txtRequestID.setFocusable(false);
        pnlRequestFields.add(txtRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 6, 205, -1));
        pnlRequestFields.add(startDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, -1));

        endDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endDatePickerPropertyChange(evt);
            }
        });
        pnlRequestFields.add(endDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        btnSendRequest.setBackground(new java.awt.Color(0, 204, 51));
        btnSendRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSendRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnSendRequest.setText("Gửi");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        pnlButton.add(btnSendRequest);

        btnCancel.setBackground(new java.awt.Color(153, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButton.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRequestFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRequestFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        try{
            String ID = txtRequestID.getText().trim();
            String datereq = txtRequestDate.getText().trim();
            String senderID = reqBUS.getEmployeeIDbyUserID(SessionDTO.getCurrentUser().getUserID());
            
            LocalDate date = LocalDate.parse(datereq);
            
            Date startDate = startDatePicker.getDate();

            if (startDate == null) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày bắt đầu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Dừng xử lý tiếp theo nếu cần
            }

            // Chuyển startDate sang LocalDate
            LocalDate startLocalDate = startDate.toInstant()
                                                .atZone(ZoneId.systemDefault())
                                                .toLocalDate();

            // Lấy và chuyển endDate nếu có
            Date endDate = endDatePicker.getDate();
            LocalDate endLocalDate = null;
            if (endDate != null) {
                endLocalDate = endDate.toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
            }
            
            if (!startLocalDate.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải sau ngày hiện tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Nếu có endDate, kiểm tra endDate > startDate
            if (endLocalDate != null && !endLocalDate.isAfter(startLocalDate)) {
                JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String reason = txtReason.getText().trim();
            if(reason == null || reason.trim().isEmpty()){
                JOptionPane.showMessageDialog(AddRequest.this, "Vui lòng nhập lí do");
                return;
            }
            String type = (String) cbRequestType.getSelectedItem();
            // tạo đơn mới
            RequestDTO newreq = new RequestDTO();
            newreq.setRequestId(ID);
            newreq.setEmployeeId(senderID);
            newreq.setLeaveStartDate(startLocalDate);
            newreq.setLeaveEndDate(endLocalDate);
            newreq.setRequestType(type);
            newreq.setReason(reason);
            newreq.setRequestDate(date);
            newreq.setStatus("Chờ duyệt");
            
            boolean success = reqBUS.addRequest(newreq);
            if (success) {
            JOptionPane.showMessageDialog(AddRequest.this, "Tạo đơn thành công với mã: " + ID);
            dispose(); // Đóng form nếu thành công
        } else {
            JOptionPane.showMessageDialog(AddRequest.this, "Tạo đơn thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        }catch( Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void endDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endDatePickerPropertyChange
        
    }//GEN-LAST:event_endDatePickerPropertyChange

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddRequest dialog = new AddRequest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> cbRequestType;
    private com.toedter.calendar.JDateChooser endDatePicker;
    private javax.swing.JLabel lblLeaveEndDate;
    private javax.swing.JLabel lblLeaveStartDate;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblRequestDate;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblRequestType;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlRequest;
    private javax.swing.JPanel pnlRequestFields;
    private com.toedter.calendar.JDateChooser startDatePicker;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtRequestDate;
    private javax.swing.JTextField txtRequestID;
    // End of variables declaration//GEN-END:variables
}
