/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Requests;

import com.pharmacy.app.BUS.RequestBUS;
import com.pharmacy.app.DTO.RequestDTO;
import com.pharmacy.app.DTO.SessionDTO;
import com.pharmacy.app.GUI.Sales.PaymentDialog;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author phong
 */
public class EmployeeRequests extends javax.swing.JPanel {
    RequestBUS reqBUS = new RequestBUS();
    /**
     * Creates new form EmployeeRequests
     */
    public EmployeeRequests() {
        initComponents();
        centerTableContent(tblRequest);
        centerTableContent(tblListRequest);
        tblRequest.setDefaultEditor(Object.class, null);
        tblListRequest.setDefaultEditor(Object.class, null);
        loadReqList();
        loadReq();
        if (SessionDTO.getCurrentUser().getRoleID().equals("ROLE003")) {
             jTabbedPane1.setEnabledAt(1, false);
        }  
    }
    
    
    private void loadReq(){
        String userid = SessionDTO.getCurrentUser().getUserID();
        ArrayList<RequestDTO> reqList = reqBUS.getAllRequestByID(userid);
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (RequestDTO req : reqList) {
            model.addRow(new Object[] {
                    stt++,
                    req.getRequestId(),
                    req.getRequestDate(),
                    req.getRequestType(),
                    req.getStatus()
            });
        }
    }
    
    
    private void loadReqList() {
        ArrayList<RequestDTO> reqList = reqBUS.getAllRequest();
        DefaultTableModel model = (DefaultTableModel) tblListRequest.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (RequestDTO req : reqList) {
            model.addRow(new Object[] {
                    stt++,
                    req.getRequestId(),
                    req.getEmployeeId(),
                    req.getRequestDate(),
                    req.getRequestType(),
                    req.getStatus()
            });
        }
    }
    
    private void centerTableContent(JTable table) {
        // Căn giữa tiêu đề
        JTableHeader header = table.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Căn giữa nội dung
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        selfReqPn = new javax.swing.JPanel();
        pnlRequest1 = new javax.swing.JPanel();
        txtSearchRequest = new javax.swing.JTextField();
        cbRequestType = new javax.swing.JComboBox<>();
        pnlRequestButton = new javax.swing.JPanel();
        btnAddRequest = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        pnlRequest2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        reqListPn = new javax.swing.JPanel();
        pnlRequest3 = new javax.swing.JPanel();
        txtSearchRequest1 = new javax.swing.JTextField();
        cbRequestType1 = new javax.swing.JComboBox<>();
        pnlRequestButton1 = new javax.swing.JPanel();
        btnRefesh1 = new javax.swing.JButton();
        btnPdf1 = new javax.swing.JButton();
        pnlRequest4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListRequest = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 514));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        selfReqPn.setBackground(new java.awt.Color(255, 255, 255));
        selfReqPn.setLayout(new java.awt.BorderLayout());

        pnlRequest1.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequest1.setToolTipText("");
        pnlRequest1.setPreferredSize(new java.awt.Dimension(607, 40));
        pnlRequest1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        txtSearchRequest.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchRequest.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchRequest.setText("Tìm kiếm");
        txtSearchRequest.setHighlighter(null);
        txtSearchRequest.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchRequest.setPreferredSize(new java.awt.Dimension(250, 22));
        txtSearchRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchRequestActionPerformed(evt);
            }
        });
        pnlRequest1.add(txtSearchRequest);

        cbRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chờ duyệt", "Đã duyệt", "Không duyệt" }));
        cbRequestType.setFocusable(false);
        cbRequestType.setMinimumSize(new java.awt.Dimension(80, 22));
        cbRequestType.setPreferredSize(new java.awt.Dimension(105, 22));
        cbRequestType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequestTypeActionPerformed(evt);
            }
        });
        pnlRequest1.add(cbRequestType);

        pnlRequestButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequestButton.setPreferredSize(new java.awt.Dimension(300, 35));
        pnlRequestButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnAddRequest.setText("Tạo");
        btnAddRequest.setFocusable(false);
        btnAddRequest.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddRequest.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddRequest.setPreferredSize(new java.awt.Dimension(72, 22));
        btnAddRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRequestActionPerformed(evt);
            }
        });
        pnlRequestButton.add(btnAddRequest);

        btnRefesh.setText("Tải lại");
        btnRefesh.setFocusable(false);
        btnRefesh.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefesh.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefesh.setPreferredSize(new java.awt.Dimension(72, 22));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        pnlRequestButton.add(btnRefesh);

        pnlRequest1.add(pnlRequestButton);

        selfReqPn.add(pnlRequest1, java.awt.BorderLayout.NORTH);

        pnlRequest2.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequest2.setPreferredSize(new java.awt.Dimension(600, 400));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(670, 402));

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã đơn", "Ngày gửi đơn", "Loại đơn", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequest.setFocusable(false);
        tblRequest.setMinimumSize(new java.awt.Dimension(500, 80));
        tblRequest.setPreferredSize(new java.awt.Dimension(670, 502));
        tblRequest.setRowHeight(30);
        tblRequest.setShowGrid(true);
        tblRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRequest);
        if (tblRequest.getColumnModel().getColumnCount() > 0) {
            tblRequest.getColumnModel().getColumn(0).setResizable(false);
            tblRequest.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnlRequest2Layout = new javax.swing.GroupLayout(pnlRequest2);
        pnlRequest2.setLayout(pnlRequest2Layout);
        pnlRequest2Layout.setHorizontalGroup(
            pnlRequest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        pnlRequest2Layout.setVerticalGroup(
            pnlRequest2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        selfReqPn.add(pnlRequest2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Đơn từ cá nhân", selfReqPn);

        reqListPn.setBackground(new java.awt.Color(255, 255, 255));
        reqListPn.setLayout(new java.awt.BorderLayout());

        pnlRequest3.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequest3.setToolTipText("");
        pnlRequest3.setPreferredSize(new java.awt.Dimension(607, 40));
        pnlRequest3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        txtSearchRequest1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchRequest1.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchRequest1.setText("Tìm kiếm");
        txtSearchRequest1.setHighlighter(null);
        txtSearchRequest1.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchRequest1.setPreferredSize(new java.awt.Dimension(250, 22));
        txtSearchRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchRequest1ActionPerformed(evt);
            }
        });
        pnlRequest3.add(txtSearchRequest1);

        cbRequestType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chờ duyệt", "Đã duyệt", "Không duyệt" }));
        cbRequestType1.setFocusable(false);
        cbRequestType1.setMinimumSize(new java.awt.Dimension(80, 22));
        cbRequestType1.setPreferredSize(new java.awt.Dimension(105, 22));
        cbRequestType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequestType1ActionPerformed(evt);
            }
        });
        pnlRequest3.add(cbRequestType1);

        pnlRequestButton1.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequestButton1.setPreferredSize(new java.awt.Dimension(300, 35));
        pnlRequestButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnRefesh1.setText("Tải lại");
        btnRefesh1.setFocusable(false);
        btnRefesh1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefesh1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefesh1.setPreferredSize(new java.awt.Dimension(72, 22));
        btnRefesh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefesh1ActionPerformed(evt);
            }
        });
        pnlRequestButton1.add(btnRefesh1);

        btnPdf1.setText("In PDF");
        btnPdf1.setFocusable(false);
        btnPdf1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setPreferredSize(new java.awt.Dimension(72, 22));
        btnPdf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdf1ActionPerformed(evt);
            }
        });
        pnlRequestButton1.add(btnPdf1);

        pnlRequest3.add(pnlRequestButton1);

        reqListPn.add(pnlRequest3, java.awt.BorderLayout.NORTH);

        pnlRequest4.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequest4.setPreferredSize(new java.awt.Dimension(600, 439));
        pnlRequest4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(670, 402));

        tblListRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã đơn", "Mã nhân viên", "Ngày gửi đơn", "Loại đơn", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListRequest.setFocusable(false);
        tblListRequest.setMinimumSize(new java.awt.Dimension(500, 80));
        tblListRequest.setPreferredSize(new java.awt.Dimension(670, 500));
        tblListRequest.setRowHeight(30);
        tblListRequest.setShowGrid(true);
        tblListRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListRequest);

        pnlRequest4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        reqListPn.add(pnlRequest4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Danh sách đơn từ", reqListPn);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchRequestActionPerformed

    private void cbRequestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequestTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRequestTypeActionPerformed

    private void btnAddRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRequestActionPerformed
        AddRequest addDialog = new AddRequest((JFrame) SwingUtilities.getWindowAncestor(this), true);
        addDialog.setLocationRelativeTo(null);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnAddRequestActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        loadReq();
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void txtSearchRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRequest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchRequest1ActionPerformed

    private void cbRequestType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequestType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRequestType1ActionPerformed

    private void btnRefesh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefesh1ActionPerformed
        loadReqList();
    }//GEN-LAST:event_btnRefesh1ActionPerformed

    private void btnPdf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdf1ActionPerformed
        try {
            // Get table model
            DefaultTableModel model = (DefaultTableModel) tblListRequest.getModel();

            // Use the PDFExporter utility class to export employee data
            com.pharmacy.app.Utils.PDFExporter.exportRequestsToPDF(this, model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Lỗi khi xuất PDF: " + e.getMessage(),
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPdf1ActionPerformed

    private void tblRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = tblRequest.getSelectedRow();
            if (row >= 0) {
                String ID = tblRequest.getValueAt(row, 1).toString();
                RequestDTO selectedProduct = reqBUS.getRequestByID(ID);

                // Mở dialog
                Frame frame = JOptionPane.getFrameForComponent(tblRequest);
                UpdateRequest dialog = new UpdateRequest(frame, true, selectedProduct);
                dialog.setLocationRelativeTo(frame);
                dialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_tblRequestMouseClicked

    private void tblListRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListRequestMouseClicked
    if (evt.getButton() == MouseEvent.BUTTON1) {
                int row = tblListRequest.getSelectedRow();
                if (row >= 0) {
                    String ID = tblListRequest.getValueAt(row, 1).toString();
                    RequestDTO selectedProduct = reqBUS.getRequestByID(ID);

                    // Mở dialog
                    Frame frame = JOptionPane.getFrameForComponent(tblListRequest);
                    UpdateRequest dialog = new UpdateRequest(frame, true, selectedProduct);
                    dialog.setLocationRelativeTo(frame);
                    dialog.setVisible(true);
                }
            }
    }//GEN-LAST:event_tblListRequestMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRequest;
    private javax.swing.JButton btnPdf1;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnRefesh1;
    private javax.swing.JComboBox<String> cbRequestType;
    private javax.swing.JComboBox<String> cbRequestType1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlRequest1;
    private javax.swing.JPanel pnlRequest2;
    private javax.swing.JPanel pnlRequest3;
    private javax.swing.JPanel pnlRequest4;
    private javax.swing.JPanel pnlRequestButton;
    private javax.swing.JPanel pnlRequestButton1;
    private javax.swing.JPanel reqListPn;
    private javax.swing.JPanel selfReqPn;
    private javax.swing.JTable tblListRequest;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtSearchRequest;
    private javax.swing.JTextField txtSearchRequest1;
    // End of variables declaration//GEN-END:variables
}
