/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Promo;
import com.pharmacy.app.BUS.PromotionBUS;
import com.pharmacy.app.DTO.PromotionDTO;
import com.pharmacy.app.Utils.PDFExporter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 
 * @author Giai Cuu Li San
 */
public class HomePromo extends javax.swing.JPanel{
    private PromotionBUS promoBUS = new PromotionBUS(); // Lớp xử lý nghiệp vụ cho Promo
    private ArrayList<PromotionDTO> promotionList = new ArrayList<>();
    private ArrayList<PromotionDTO> promotionListByType = new ArrayList<>();

    public HomePromo() {
        initComponents();
        loadAllData();
        centerTableContent(tblPromo);      
        adjustTableHeight(tblPromo, jScrollPane2);
        
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchPromo();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchPromo();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchPromo();

            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        plSearch = new javax.swing.JPanel();
        cbSort = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        plButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        btnPrintPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(800, 100));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));
        plHeader.setPreferredSize(new java.awt.Dimension(1200, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ MÃ KHUYẾN MÃI");
        jLabel2.setPreferredSize(new java.awt.Dimension(1200, 40));
        plHeader.add(jLabel2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 80));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(300, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 50));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đổi điểm", "Giảm phần trăm" }));
        cbSort.setMinimumSize(new java.awt.Dimension(100, 30));
        cbSort.setPreferredSize(new java.awt.Dimension(90, 30));
        cbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSortActionPerformed(evt);
            }
        });
        plSearch.add(cbSort);

        txtSearch.setMaximumSize(new java.awt.Dimension(300, 30));
        txtSearch.setMinimumSize(new java.awt.Dimension(100, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 30));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        plSearch.add(txtSearch);

        jPanel2.add(plSearch);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(300, 70));
        plButton.setMinimumSize(new java.awt.Dimension(200, 70));
        plButton.setPreferredSize(new java.awt.Dimension(300, 50));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        plButton.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefesh.setText("Làm mới");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });
        plButton.add(btnRefesh);

        btnPrintPDF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrintPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        btnPrintPDF.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrintPDF.setMaximumSize(new java.awt.Dimension(90, 30));
        btnPrintPDF.setMinimumSize(new java.awt.Dimension(90, 30));
        btnPrintPDF.setPreferredSize(new java.awt.Dimension(40, 30));
        btnPrintPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintPDFActionPerformed(evt);
            }
        });
        plButton.add(btnPrintPDF);

        jPanel2.add(plButton);

        plHeader.add(jPanel2);

        add(plHeader, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1200, 760));

        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KM01", "Sale Ngày Nhà Thuốc VN", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Loại khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableColumnModel columnModel = tblPromo.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setPreferredWidth(50);
        tblPromo.setMaximumSize(new java.awt.Dimension(700, 600));
        tblPromo.setMinimumSize(new java.awt.Dimension(700, 450));
        tblPromo.setPreferredSize(new java.awt.Dimension(1200, 1000));
        tblPromo.setRowHeight(30);
        tblPromo.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblPromo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        int selected_row = tblPromo.getSelectedRow();
        System.out.println(selected_row);
        if (selected_row != -1) {
            String promoId = tblPromo.getValueAt(selected_row, 0).toString();
            PromotionDTO promo = promoBUS.selectById(promoId);  // lấy chi tiết

            if (promo != null) {
                PromoDetail dialog = new PromoDetail((JFrame) SwingUtilities.getWindowAncestor(this), true, this, promo);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin khuyến mãi.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
      
    }//GEN-LAST:event_tblPromoMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddPromo dialog = new AddPromo(this);
        dialog.setVisible(true); // Hiển thị cửa sổ chi tiết
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSortActionPerformed
        String selectedType = cbSort.getSelectedItem().toString();
        if (selectedType.equals("Tất cả")){
            loadAllData(); 
        } else {
            loadDataByType(selectedType);
        }
    }//GEN-LAST:event_cbSortActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        cbSort.setSelectedItem("Tất cả");
        txtSearch.setText("");
        loadAllData();
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void btnPrintPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPDFActionPerformed
        try {
            // Get table model
            DefaultTableModel model = (DefaultTableModel) tblPromo.getModel();

            // Use the PDFExporter utility class to export employee data
            com.pharmacy.app.Utils.PDFExporter.exportPromotionsToPDF(this, model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Lỗi khi xuất PDF: " + e.getMessage(),
                "Lỗi",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintPDFActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
    
    
    public void adjustTableHeight(JTable table, JScrollPane scrollPane) {
        int rowCount = table.getRowCount();
        int rowHeight = table.getRowHeight();

        // Tính tổng chiều cao cần thiết cho tất cả dòng
        int totalHeight = rowCount * rowHeight;

        // Đặt kích thước preferred viewport cho bảng
        table.setPreferredScrollableViewportSize(new Dimension(
            table.getPreferredScrollableViewportSize().width,
            totalHeight
        ));

        // Làm cho bảng lấp đầy JScrollPane
        table.setFillsViewportHeight(true);

        // Gọi lại validate để cập nhật layout
        scrollPane.revalidate();
    }

    // Dùng cho combobox
    public void loadDataByType(String type) {
        promotionListByType = promoBUS.getPromosByType(type); // Lấy danh sách mã giảm giá từ PromoBUS
        showDataToTable(promotionListByType);
    }

    public void showDataToTable(ArrayList<PromotionDTO> list) {
        DefaultTableModel model = (DefaultTableModel) tblPromo.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        for (PromotionDTO promo : list) {
            model.addRow(new Object[]{
                promo.getPromotionId(),
                promo.getProgramName(),
                promo.getPromotionType(),
                promo.getStartDate(),
                promo.getEndDate()
            });
        }
    }
    
    // Dùng cho
    public void loadAllData() {
        promotionList = promoBUS.getAllPromos();
        showDataToTable(promotionList);
    }
    
    private void searchPromo() {
        String keyword = txtSearch.getText();
        ArrayList<PromotionDTO> result = promoBUS.searchAll(keyword);
        showDataToTable(result);
    }
    
    private void centerTableContent(JTable table) {
        // Căn giữa tiêu đề
        table.setSelectionBackground(new Color(57,105,138));
        JTableHeader header = table.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Căn giữa nội dung
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPrintPDF;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
