/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Importing;

import com.pharmacy.app.BUS.MedicalProductsBUS;
import com.pharmacy.app.BUS.PurchaseOrderDetailsBUS;
import com.pharmacy.app.BUS.SuplierInvoiceDetailsBUS;
import com.pharmacy.app.BUS.SuplierInvoicesBUS;
import com.pharmacy.app.DAO.SupplierInvoiceDetailsDAO;
import com.pharmacy.app.DTO.MedicalProductsDTO;
import com.pharmacy.app.DTO.PurchaseOrderDTO;
import com.pharmacy.app.DTO.PurchaseOrderDetailsDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class ConfirmStockIn extends javax.swing.JDialog {

    private SuplierInvoicesBUS supInvBUS = new SuplierInvoicesBUS();
    private SuplierInvoiceDetailsBUS supInvDeBUS = new SuplierInvoiceDetailsBUS();
    private PurchaseOrderDetailsBUS poDeBUS = new PurchaseOrderDetailsBUS();
    private MedicalProductsBUS productBUS = new MedicalProductsBUS();

    /**
     * Creates new form ConfirmStockIn
     */
    public ConfirmStockIn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTbl = new javax.swing.JTable();
        importBtn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPOid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManagerID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        txtSup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(822, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(822, 407));

        detailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã thuốc", "Tên thuốc", "Số lượng", "Mã lô thuốc", "Giá nhập", "Số lượng thực nhận", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailsTbl.setPreferredSize(new java.awt.Dimension(600, 402));
        detailsTbl.setRowHeight(30);
        detailsTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(detailsTbl);
        if (detailsTbl.getColumnModel().getColumnCount() > 0) {
            detailsTbl.getColumnModel().getColumn(0).setMinWidth(30);
            detailsTbl.getColumnModel().getColumn(0).setPreferredWidth(40);
            detailsTbl.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        importBtn.setBackground(new java.awt.Color(0, 204, 51));
        importBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        importBtn.setForeground(new java.awt.Color(255, 255, 255));
        importBtn.setText("NHẬP KHO");
        importBtn.setEnabled(false);

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("HỦY ĐƠN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã đơn:");

        txtPOid.setEditable(false);
        txtPOid.setText("DH001");

        jLabel3.setText("Nhà cung cấp:");

        txtManagerID.setEditable(false);
        txtManagerID.setText("NV001");

        jLabel6.setText("Người lập:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("TỔNG THÀNH TIỀN:");

        txtSum.setEditable(false);
        txtSum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSum.setText("0");

        jLabel7.setText("Mã phiếu nhập:");

        txtInvoiceID.setEditable(false);
        txtInvoiceID.setText("PN001");
        txtInvoiceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceIDActionPerformed(evt);
            }
        });

        txtSup.setEditable(false);
        txtSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(importBtn)
                                .addGap(50, 50, 50)
                                .addComponent(jButton8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(txtPOid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPOid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importBtn)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("XÁC NHẬN NHẬP HÀNG");
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadStockInDialog(PurchaseOrderDTO selectedPO){
        txtInvoiceID.setText(supInvBUS.generateNextProductID());
        txtManagerID.setText(selectedPO.getManagerUserID());
        txtPOid.setText(selectedPO.getPoID());
        txtSup.setText(selectedPO.getSupplierID());
        
       // Load chi tiết PO
        ArrayList<PurchaseOrderDetailsDTO> detailsList = poDeBUS.getAllPOdetails(selectedPO.getPoID());
        DefaultTableModel model = (DefaultTableModel) detailsTbl.getModel();
        model.setRowCount(0); // clear bảng

        int stt = 1;
        for (PurchaseOrderDetailsDTO detail : detailsList) {
            String productID = detail.getproductID();
            String productName = ""; // lấy từ MedicalProductsDTO

            MedicalProductsDTO product = productBUS.getProductByID(productID);
            if (product != null) {
                productName = product.getName();
            }

            model.addRow(new Object[]{
                stt++,
                productID,
                productName,
                detail.getQuantity(),  // Số lượng từ đơn hàng
                "",                    // Mã lô thuốc - nhập tay
                0.0,                    // Giá nhập - nhập tay
                0,                    // SL thực nhận - nhập tay
                0.0                     // Thành tiền - tính sau
            });
        }
        addPriceCalculationListener(detailsTbl);
    }
    private boolean isUpdating = false;

   public void addPriceCalculationListener(JTable table) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();

    table.getModel().addTableModelListener(e -> {
        if (isUpdating || e.getType() != TableModelEvent.UPDATE) return;

        int row = e.getFirstRow();
        isUpdating = true;

        try {
            Object priceObj = model.getValueAt(row, 4);    // Giá nhập (String -> float)
            Object quantityObj = model.getValueAt(row, 5); // Số lượng (int)

            if (priceObj != null && quantityObj != null &&
                !priceObj.toString().isBlank() && !quantityObj.toString().isBlank()) {

                float price = Float.parseFloat(priceObj.toString().replace(",", "").trim());
                int quantity = Integer.parseInt(quantityObj.toString().replace(",", "").trim());

                float total = price * quantity;
                model.setValueAt(total, row, 6); // Cột 6: Thành tiền
            } else {
                model.setValueAt(null, row, 6); // Clear nếu thiếu dữ liệu
            }

        } catch (NumberFormatException ex) {
            model.setValueAt(null, row, 6); // Clear nếu lỗi định dạng
        } finally {
            isUpdating = false;
        }

        calculateSum(table);
        importBtn.setEnabled(isAllRequiredCellsFilled(model));
    });
}

public void calculateSum(JTable table) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    float sum = 0f;

    for (int i = 0; i < model.getRowCount(); i++) {
        Object val = model.getValueAt(i, 6); // Thành tiền ở cột 6

        if (val != null) {
            try {
                float value = (val instanceof Number) ?
                    ((Number) val).floatValue() :
                    Float.parseFloat(val.toString());
                sum += value;
            } catch (NumberFormatException ex) {
                // Bỏ qua nếu lỗi định dạng
            }
        }
    }

    txtSum.setText(String.format("%.2f", sum));
}

public boolean isAllRequiredCellsFilled(DefaultTableModel model) {
    for (int i = 0; i < model.getRowCount(); i++) {
        for (int col = 4; col <= 6; col++) {
            Object val = model.getValueAt(i, col);
            if (val == null || val.toString().trim().isEmpty()) {
                return false; // Nếu có bất kỳ ô nào trống thì chưa đủ
            }
        }
    }
    return true;
}


    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtInvoiceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceIDActionPerformed

    private void txtSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmStockIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmStockIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmStockIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmStockIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmStockIn dialog = new ConfirmStockIn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailsTbl;
    private javax.swing.JButton importBtn;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtManagerID;
    private javax.swing.JTextField txtPOid;
    private javax.swing.JTextField txtSum;
    private javax.swing.JTextField txtSup;
    // End of variables declaration//GEN-END:variables
}
