/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.Payroll;

import com.pharmacy.app.BUS.EmployeeBUS;
import com.pharmacy.app.BUS.PayrollBUS;
import com.pharmacy.app.BUS.PayrollDetailsBUS;
import com.pharmacy.app.BUS.SalaryComponentsBUS;
import com.pharmacy.app.DTO.EmployeeDTO;
import com.pharmacy.app.DTO.PayrollDTO;
import com.pharmacy.app.DTO.PayrollDetailsDTO;
import com.pharmacy.app.DTO.SalaryComponentsDTO;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phong
 */
public class PayrollDetails extends javax.swing.JDialog {
    private PayrollBUS payrollBUS;
    private PayrollDetailsBUS payrollDetailsBUS;
    private EmployeeBUS employeeBUS;
    private PayrollDTO selectedPayroll;

    /**
     * Creates new form AddPayroll
     * @param parent
     * @param modal
     */
    public PayrollDetails(JFrame parent, boolean modal, PayrollDTO selectedPayroll) {
        super(parent, modal);
        this.selectedPayroll = selectedPayroll;
        this.payrollBUS = new PayrollBUS();
        this.payrollDetailsBUS = new PayrollDetailsBUS();
        this.employeeBUS = new EmployeeBUS();
        initComponents();
        displayPayrollData();
        displayPayrollDetails();
    }
    
    public PayrollDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.payrollBUS = new PayrollBUS();
        this.payrollDetailsBUS = new PayrollDetailsBUS();
        this.employeeBUS = new EmployeeBUS();
        initComponents();
    }
    
    private void displayPayrollData() {
        if (selectedPayroll != null) {
            // Display basic payroll information
            txtEmployeeID.setText(selectedPayroll.getEmployeeID());

            // Get employee name
            String employeeID = selectedPayroll.getEmployeeID();
            EmployeeDTO employee = employeeBUS.getEmployeeByID(employeeID);
            String employeeName = (employee != null) ? employee.getName() : "Unknown";
            txtEmployeeName.setText(employeeName);

            // Format and display total salary
            NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
            txtTotal.setText(currencyFormat.format(selectedPayroll.getTotalSalary()));

            // Display status
            txtStatus.setText(selectedPayroll.getStatus() ? "Đã thanh toán" : "Chưa thanh toán");

            // Format and display payment date
            if (selectedPayroll.getPayDate() != null) {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
                txtDate.setText(selectedPayroll.getPayDate().format(formatter));
            } else {
                txtDate.setText("Chưa có");
            }
        }
    }

    private void displayPayrollDetails() {
        if (selectedPayroll != null) {
            // Initialize SalaryComponentsBUS and load data
            SalaryComponentsBUS componentsBUS = new SalaryComponentsBUS();
            componentsBUS.loadComponentsList();

            // Get payroll details
            ArrayList<PayrollDetailsDTO> payrollDetails = payrollDetailsBUS.getPayrollDetailsByPayrollID(selectedPayroll.getPayrollID());

            // Set up table model
            DefaultTableModel model = (DefaultTableModel) tblPayrollComponent.getModel();
            model.setRowCount(0); // Clear existing rows

            // Format currency
            NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));

            // Add data to table
            for (PayrollDetailsDTO detail : payrollDetails) {
                Object[] row = new Object[3];

                // Get component name instead of ID
                SalaryComponentsDTO component = componentsBUS.getComponentByID(detail.getComponentID());
                row[0] = (component != null) ? component.getName() : detail.getComponentID();

                // Value (could be days/hours)
                row[1] = detail.getValue();

                // Amount
                row[2] = currencyFormat.format(detail.getAmount());

                model.addRow(row);
            }

            // Auto-resize columns
            tblPayrollComponent.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPayroll = new javax.swing.JPanel();
        lblPayroll = new javax.swing.JLabel();
        pnlEmployeeInfo = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblEmployeeName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        pnlPayrollComponent = new javax.swing.JPanel();
        spPayrollComponent = new javax.swing.JScrollPane();
        tblPayrollComponent = new javax.swing.JTable();
        pnlButton = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblPayroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPayroll.setText("BẢNG LƯƠNG");
        pnlPayroll.add(lblPayroll);

        pnlEmployeeInfo.setLayout(new java.awt.GridBagLayout());

        lblEmployeeID.setText("Mã nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        pnlEmployeeInfo.add(lblEmployeeID, gridBagConstraints);

        txtEmployeeID.setEditable(false);
        txtEmployeeID.setFocusable(false);
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlEmployeeInfo.add(txtEmployeeID, gridBagConstraints);

        lblEmployeeName.setText("Tên nhân viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 20);
        pnlEmployeeInfo.add(lblEmployeeName, gridBagConstraints);

        txtEmployeeName.setEditable(false);
        txtEmployeeName.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlEmployeeInfo.add(txtEmployeeName, gridBagConstraints);

        lblTotal.setText("Lương thực nhận:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        pnlEmployeeInfo.add(lblTotal, gridBagConstraints);

        txtTotal.setEditable(false);
        txtTotal.setFocusable(false);
        txtTotal.setMinimumSize(new java.awt.Dimension(72, 22));
        txtTotal.setPreferredSize(new java.awt.Dimension(72, 22));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlEmployeeInfo.add(txtTotal, gridBagConstraints);

        lblStatus.setText("Trạng thái:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        pnlEmployeeInfo.add(lblStatus, gridBagConstraints);

        txtStatus.setEditable(false);
        txtStatus.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlEmployeeInfo.add(txtStatus, gridBagConstraints);

        lblDate.setText("Ngày trả lương:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 20);
        pnlEmployeeInfo.add(lblDate, gridBagConstraints);

        txtDate.setEditable(false);
        txtDate.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        pnlEmployeeInfo.add(txtDate, gridBagConstraints);

        pnlPayrollComponent.setPreferredSize(new java.awt.Dimension(500, 439));
        pnlPayrollComponent.setLayout(new java.awt.BorderLayout());

        spPayrollComponent.setMinimumSize(new java.awt.Dimension(452, 20));

        tblPayrollComponent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Thành phần lương", "Ngày/Giờ", "Số tiền"
            }
        ));
        tblPayrollComponent.setEnabled(false);
        tblPayrollComponent.setFocusable(false);
        spPayrollComponent.setViewportView(tblPayrollComponent);

        pnlPayrollComponent.add(spPayrollComponent, java.awt.BorderLayout.CENTER);

        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        btnCancel.setBackground(new java.awt.Color(153, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButton.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlEmployeeInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPayrollComponent, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlEmployeeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlPayrollComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PayrollDetails dialog = new PayrollDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlEmployeeInfo;
    private javax.swing.JPanel pnlPayroll;
    private javax.swing.JPanel pnlPayrollComponent;
    private javax.swing.JScrollPane spPayrollComponent;
    private javax.swing.JTable tblPayrollComponent;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
