/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app;

import com.pharmacy.app.BUS.EmployeeBUS;
import com.pharmacy.app.BUS.UserBUS;
import com.pharmacy.app.BUS.WorkShiftBUS;
import com.pharmacy.app.DTO.AttendanceDTO;
import com.pharmacy.app.DTO.EmployeeDTO;
import com.pharmacy.app.DTO.SessionDTO;
import com.pharmacy.app.DTO.UserDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author BOI QUAN
 */
public class attendance extends javax.swing.JDialog {
    DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("EEEE, dd/MM/yyyy HH:mm:ss");
    WorkShiftBUS workBUS = new WorkShiftBUS();
    /**
     * Creates new form attendance
     * @param parent
     * @param modal
     */
    public attendance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        timer.start();
        
        
        UserDTO currentUser = SessionDTO.getCurrentUser();
        EmployeeBUS emBUS = new EmployeeBUS();
        EmployeeDTO employee = emBUS.getEmployeeByUserID(currentUser.getUserID());
        txtEmployeeId.setText(employee.getEmployeeID());
        
        isCheckInOut(txtEmployeeId.getText());
//        System.out.println("currentUser: " + employee.getEmployeeID());   
    }
    
    Timer timer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
            LocalDateTime date = LocalDateTime.now();
            lblDatetime.setText(date.format(FORMATTER));
        }  
    });
    public final void isCheckInOut (String employeeID){
        boolean isCheckIn = workBUS.isCheckIn(txtEmployeeId.getText());
        boolean isCheckOut = workBUS.isCheckOut(txtEmployeeId.getText());
        btnCheckIn.setEnabled(!isCheckIn);
        btnCheckOut.setEnabled(!isCheckOut);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDatetime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtEmployeeId = new javax.swing.JTextField();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chấm công");
        jLabel1.setPreferredSize(new java.awt.Dimension(62, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        lblDatetime.setText("Chủ nhật, ngày 10/05/2025");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(lblDatetime, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 180));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        txtEmployeeId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtEmployeeId.setPreferredSize(new java.awt.Dimension(64, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 30);
        jPanel2.add(txtEmployeeId, gridBagConstraints);

        btnCheckIn.setText("Check in");
        btnCheckIn.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel2.add(btnCheckIn, gridBagConstraints);

        btnCheckOut.setText("Check out");
        btnCheckOut.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        jPanel2.add(btnCheckOut, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        String employeeId = txtEmployeeId.getText();
        WorkShiftBUS bus = new WorkShiftBUS();
   
        if(employeeId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã nhân viên");
            return;
        }
        AttendanceDTO attendance = new AttendanceDTO();
        attendance.setEmployeeId(employeeId);
        
        boolean success = bus.checkIn(attendance);
        if(success){
            JOptionPane.showMessageDialog(null, "Check-in thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Check-in thất bại");
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        String employeeId = txtEmployeeId.getText();
        WorkShiftBUS bus = new WorkShiftBUS();
        
        if(employeeId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã nhân viên");
            return;
        }
        
        boolean success = bus.checkOut(employeeId);
        if(success){
            JOptionPane.showMessageDialog(null, "Check-out thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Check-out thất bại");
        }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                attendance dialog = new attendance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDatetime;
    private javax.swing.JTextField txtEmployeeId;
    // End of variables declaration//GEN-END:variables
}
