/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pharmacy.app.GUI.User;

import com.pharmacy.app.BUS.RoleBUS;
import com.pharmacy.app.BUS.UserBUS;
import com.pharmacy.app.DTO.RoleDTO;
import com.pharmacy.app.DTO.UserDTO;
import com.pharmacy.app.Utils.UserValidation;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author phong
 */
public class UpdateUser extends javax.swing.JDialog {
    private UserDTO userDTO;
    private RoleBUS roleBUS;
    private UserBUS userBUS;
    private ButtonGroup statusGroup;

    /**
     * Creates new form UpdateUser
     * @param parent 
     * @param modal
     * @param user
     */
    public UpdateUser(java.awt.Frame parent, boolean modal, UserDTO user) {
        super(parent, modal);
        initComponents();
        this.userDTO = user;

        // Initialize BUS classes
        roleBUS = new RoleBUS();
        roleBUS.loadRoleList();
        userBUS = new UserBUS();

        // Group radio buttons
        setupRadioButtons();

        // Load roles and set current data
//        loadRoles();
        setData(user);
    }

    private UpdateUser(JFrame jFrame, boolean b) {
        super(jFrame, b);
        initComponents();
    }
    
    // Setup radio button group
    private void setupRadioButtons() {
        // Group radio buttons to ensure only one can be selected
        statusGroup = new ButtonGroup();
        statusGroup.add(rbActive);
        statusGroup.add(rbUnactive);
    }

    // Load roles into combo box
//    private void loadRoles() {
//        ArrayList<RoleDTO> roles = roleBUS.getRoleList();
//        cbUserRole.removeAllItems();
//
//        // Add each role to the combo box
//        for(RoleDTO role : roles) {
//            cbUserRole.addItem(role.getRoleName());
//        }
//    }

    // Update setData method to fully populate form with user data
    private void setData(UserDTO user) {
        txtUserID.setText(user.getUserID());
        txtUsername.setText(user.getUsername());

        // Set selected role
        RoleDTO role = roleBUS.getRoleByID(user.getRoleID());
        String roleName = (role != null) ? role.getRoleName() : "Unknown";
        cbUserRole.setSelectedItem(roleName);

        // Set user status
        if (user.getStatus()) {
            rbActive.setSelected(true);
        } else {
            rbUnactive.setSelected(true);
        }
    }
    
    // Validate form inputs
    private boolean validateForm() {
        // Validate username
        String username = txtUsername.getText().trim();
        String usernameError = UserValidation.validateUsername(username);
        if (!usernameError.isEmpty()) {
            JOptionPane.showMessageDialog(this, usernameError, "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
            return false;
        }

        // Check if username exists (only if changed)
        if (!username.equals(userDTO.getUsername())) {
            String existsError = UserValidation.validateUsernameExists(username, new com.pharmacy.app.DAO.UserDAO());
            if (!existsError.isEmpty()) {
                JOptionPane.showMessageDialog(this, existsError, "Lỗi", JOptionPane.ERROR_MESSAGE);
                txtUsername.requestFocus();
                return false;
            }
        }

        // Check if role is selected
        if (cbUserRole.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cbUserRole.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlUpdateUser = new javax.swing.JPanel();
        lblUpdateUser = new javax.swing.JLabel();
        pnlUpdateUserFields = new javax.swing.JPanel();
        lblUserID = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUserStatus = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        cbUserRole = new javax.swing.JComboBox<>();
        pnlUpdateStatus = new javax.swing.JPanel();
        rbActive = new javax.swing.JRadioButton();
        rbUnactive = new javax.swing.JRadioButton();
        pnlUpdateButton = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlUpdateUser.setLayout(new java.awt.BorderLayout());

        lblUpdateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUpdateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateUser.setText("THÔNG TIN TÀI KHOẢN");
        pnlUpdateUser.add(lblUpdateUser, java.awt.BorderLayout.CENTER);

        pnlUpdateUserFields.setLayout(new java.awt.GridBagLayout());

        lblUserID.setText("Mã người dùng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 20);
        pnlUpdateUserFields.add(lblUserID, gridBagConstraints);

        lblUsername.setText("Tên người dùng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 20);
        pnlUpdateUserFields.add(lblUsername, gridBagConstraints);

        lblRole.setText("Vai trò:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 20);
        pnlUpdateUserFields.add(lblRole, gridBagConstraints);

        lblUserStatus.setText("Trạng thái:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        pnlUpdateUserFields.add(lblUserStatus, gridBagConstraints);

        txtUserID.setEditable(false);
        txtUserID.setEnabled(false);
        txtUserID.setFocusable(false);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        pnlUpdateUserFields.add(txtUserID, gridBagConstraints);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        pnlUpdateUserFields.add(txtUsername, gridBagConstraints);

        cbUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên dược sĩ" }));
        cbUserRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUserRoleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        pnlUpdateUserFields.add(cbUserRole, gridBagConstraints);

        pnlUpdateStatus.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        rbActive.setText("Active");
        rbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActiveActionPerformed(evt);
            }
        });
        pnlUpdateStatus.add(rbActive);

        rbUnactive.setText("Inactive");
        rbUnactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUnactiveActionPerformed(evt);
            }
        });
        pnlUpdateStatus.add(rbUnactive);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.weightx = 10.0;
        pnlUpdateUserFields.add(pnlUpdateStatus, gridBagConstraints);

        pnlUpdateButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlUpdateButton.add(btnUpdate);

        btnCancel.setBackground(new java.awt.Color(153, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlUpdateButton.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlUpdateUserFields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUpdateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlUpdateUserFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cbUserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUserRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUserRoleActionPerformed

    private void rbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbActiveActionPerformed

    private void rbUnactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUnactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbUnactiveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Validate inputs
        if (!validateForm()) {
            return;
        }

        try {
            // Get updated values
            String userID = txtUserID.getText();
            String username = txtUsername.getText().trim();

            // Get selected role ID from name
            String roleName = cbUserRole.getSelectedItem().toString();
            String roleID = roleBUS.getRoleIDByName(roleName);

            // Get status value
            boolean status = rbActive.isSelected();

            // Create updated user object
            UserDTO updatedUser = new UserDTO(
                userID,
                username,
                userDTO.getPassword(), // Keep original password
                roleID,
                status
            );

            // Update user in database
            boolean result = userBUS.updateUser(updatedUser);

            if (result) {
                JOptionPane.showMessageDialog(this, 
                    "Cập nhật người dùng thành công!", 
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);

                // Close form
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Cập nhật người dùng thất bại!", 
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, 
                "Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For detaipnlUpdateFieldshttp://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdateUser dialog = new UpdateUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbUserRole;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUpdateUser;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUpdateButton;
    private javax.swing.JPanel pnlUpdateStatus;
    private javax.swing.JPanel pnlUpdateUser;
    private javax.swing.JPanel pnlUpdateUserFields;
    private javax.swing.JRadioButton rbActive;
    private javax.swing.JRadioButton rbUnactive;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
